(function (global) {
  const CONFIG = Object.freeze({
    STORAGE_KEY: 'clawbot_v21',
    LEGACY_STORAGE_KEY: 'clawbot_v2',
    STAGES: Object.freeze(['Qualified','Briefing','Proposal','Negotiation','Verbal','Closed']),
    STAGE_MULT: Object.freeze({
      Qualified: 0.30,
      Briefing: 0.50,
      Proposal: 0.70,
      Negotiation: 0.85,
      Verbal: 0.95,
      Closed: 1.0,
      Archived: 0
    }),
    DEFAULT_NBA: Object.freeze({
      Qualified: 'Send first-touch email',
      Briefing: 'Follow up within 48h',
      Proposal: 'Schedule discovery call',
      Negotiation: 'Address objections directly',
      Verbal: 'Prepare contract terms',
      Closed: 'Secure expansion opportunity',
      Archived: 'Re-qualify before outreach'
    }),
    HARD_CONSTRAINTS: Object.freeze([
      'NEVER send more than 1 outreach touch per lead per 72h',
      'NEVER discount beyond 10% without Roman approval',
      'NEVER submit proposal without Roman review',
      'NEVER represent capability Trestleboard cannot deliver',
      'NEVER use aggressive/manipulative language',
      'NEVER override MANUAL HOLD',
      'NEVER engage prospect under active legal dispute',
      'ALWAYS respect federal procurement blackout periods',
      'ALWAYS maintain ITAR compliance',
      'ALWAYS escalate GO/SES-3+/Congressional to Roman directly'
    ]),
    AGENT_DEFINITIONS: Object.freeze([
      { id: 'leadAnalyst', name: 'Lead Analyst', role: 'Pipeline Intelligence', confidence: 75 },
      { id: 'campaignStrategist', name: 'Campaign Strategist', role: 'Sequencing & Cadence', confidence: 80 },
      { id: 'copywritingAgent', name: 'Copywriting Agent', role: 'Message Crafting', confidence: 85 },
      { id: 'negotiationAgent', name: 'Negotiation Agent', role: 'Counter-Objection', confidence: 90 },
      { id: 'revenueForecaster', name: 'Revenue Forecaster', role: 'EV Modeling', confidence: 95 },
      { id: 'riskMonitor', name: 'Risk Monitor', role: 'Decay & Compliance', confidence: 60 }
    ]),
    SCENARIO_PRESETS: Object.freeze({
      outreach_freq: { label: 'Increase outreach frequency 20%', convDelta: 8, cycleDelta: -7, recommendation: 'PROCEED', confidence: 78, urgency: 1.08, notes: 'Campaign Strategist: tighten cadences across IC + DoD seeds.' },
      linkedin_pivot: { label: 'Shift primary channel to LinkedIn (IC vertical)', convDelta: 12, cycleDelta: -10, recommendation: 'PROCEED', confidence: 82, urgency: 1.05, notes: 'Lead Analyst: IC personas need Roman video context.' },
      discount_5: { label: 'Add 5% pricing discount for FY Q4 close', convDelta: 15, cycleDelta: -14, recommendation: 'CAUTION', confidence: 71, urgency: 1.0, notes: 'Negotiation Agent: secure Roman approval before any discount language.' },
      roman_touch: { label: 'Deploy Roman as personal touch on top 3 deals', convDelta: 22, cycleDelta: -21, recommendation: 'PROCEED', confidence: 89, urgency: 1.2, notes: 'Roman engages directly on highest priority stack leads.' },
      callbot: { label: 'Activate call bot on stalled email sequences', convDelta: 6, cycleDelta: -5, recommendation: 'PROCEED', confidence: 75, urgency: 1.02, notes: 'Risk Monitor: confirm disclosure + compliance.' },
      custom: { label: 'Custom scenario', convDelta: 0, cycleDelta: 0, recommendation: 'ASSESS', confidence: 70, urgency: 1, notes: '' }
    }),
    AUTH: Object.freeze({
      // SHA-256 of 'trestleboard-v21:Mufasa1945'
      passHash: 'd5670fe9909586f26781025738c1960cfc7686c01bf721144c73cf8b82465440',
      salt: 'trestleboard-v21',
      legacyPass: 'Mufasa1945',
      maxAttempts: 5,
      lockMinutes: 15,
      // Session TTL in milliseconds (8 hours)
      sessionTTL: 28800000
    })
  });

  // ─── Agent Intel Leads (USAspending.gov + public records) ────────────
  const AGENT_INTEL_LEADS = Object.freeze([
    {id:"disc_001",source:"USAspending.gov — DoD Contract Recompete",name:"Business Development Director",org:"LMI Consulting, LLC",vertical:"Defense Contractor",confidence:92,intel:"CRITICAL RECOMPETE: $83.4M WHS/OSD Strategic Communications & Admin Support contract EXPIRED July 2025. Active recompete window open NOW. LMI is the incumbent — they will be scrambling to rebuild and partner. Angle: Trestleboard as narrative/AI content subcontractor on recompete bid. Contact BD or Capture team.",linkedinSearch:"site:linkedin.com LMI Consulting strategic communications director",email:"bd@lmi.org (format — verify)",contractRef:"WHS $83.4M expired 2025-07-22",approach:"TEAMING — Position as AI-native subcontractor on their OSD recompete. Lead with 99.7% faster narrative production and IG-ready audit trail."},
    {id:"disc_002",source:"USAspending.gov — DoD Contract Expiring",name:"VP Strategic Communications",org:"HII Mission Technologies Corp",vertical:"Defense Contractor",confidence:89,intel:"RECOMPETE WINDOW: $48.7M USAF Info Ops / Applied Research contract EXPIRED Sept 2025. HII Mission Technologies is a top-tier DoD contractor. Angle: Team on USAF narrative/IO recompete.",linkedinSearch:"site:linkedin.com HII Mission Technologies strategic communications capture manager",email:"capture@hii.com (format — verify)",contractRef:"USAF $48.7M expired 2025-09-15",approach:"TEAMING — Strategic communications/narrative as add-on to their IO portfolio. Reference USAF contested information environment doctrine."},
    {id:"disc_003",source:"USAspending.gov — DHA Contract Just Expired",name:"Program Director",org:"Deloitte Consulting LLP (Defense Health Agency)",vertical:"Defense Contractor",confidence:87,intel:"HOT: $39.2M Defense Health Agency program management/comms contract EXPIRED Feb 2026. DHA is one of DoD's largest communications buyers. Contact DHA practice BD lead.",linkedinSearch:"site:linkedin.com Deloitte Defense Health Agency strategic communications director",email:"defense@deloitte.com (format — verify)",contractRef:"DHA $39.2M expired 2026-02-15",approach:"TEAMING — Offer AI narrative production as differentiator in Deloitte's DHA recompete package."},
    {id:"disc_004",source:"USAspending.gov — USAF Contract Expiring NOW",name:"Contracts & Capture Manager",org:"CACI, Inc. - Federal",vertical:"Defense Contractor",confidence:85,intel:"URGENT: $32.4M USAF IT/comms application support contract expires March 2026 — in active recompete window RIGHT NOW. CACI is a major prime — teaming opportunity for Trestleboard's narrative/comms layer.",linkedinSearch:"site:linkedin.com CACI Federal strategic communications Air Force capture",email:"businessdev@caci.com (format — verify)",contractRef:"USAF $32.4M expires 2026-03-31",approach:"TEAMING — Pitch as rapid narrative/content subcontractor on USAF recompete. CACI already knows the space; position Trestleboard as their AI edge."},
    {id:"disc_005",source:"USAspending.gov — DHA Contract Expiring THIS MONTH",name:"Director of Strategic Communications",org:"Chickasaw Aerospace, LLC",vertical:"Defense Contractor",confidence:88,intel:"EXPIRING: $15.95M DHA Director/DAG Strategic Communications, Engagements, Protocol & Archives contract expires March 2026 — THIS MONTH. 8(a) small business — they may be losing this contract or recompeting. Trestleboard can position as successor or teaming partner.",linkedinSearch:"site:linkedin.com Chickasaw Aerospace strategic communications",email:"info@chickasawaerospace.com (format — verify)",contractRef:"DHA $15.95M expires 2026-03-16",approach:"DIRECT APPROACH or TEAMING — This contract ends THIS MONTH. DHA will need a replacement. Pitch DHA directly or help Chickasaw on transition."},
    {id:"disc_006",source:"USAspending.gov — DISA Contract Just Expired",name:"BD Director",org:"Command Post Technologies, Inc.",vertical:"Defense Contractor",confidence:80,intel:"$25.8M DISA IT/comms support contract expired Feb 2026. Small business — may be looking for teaming partners. DISA is a heavy comms buyer.",linkedinSearch:"site:linkedin.com Command Post Technologies business development DISA",email:"info@commandposttechnologies.com (format — verify)",contractRef:"DISA $25.8M expired 2026-02-03",approach:"TEAMING — Approach as AI-native narrative partner for DISA recompete effort."},
    {id:"disc_007",source:"USAspending.gov — Ipsos Public Affairs Active Contract",name:"Federal Practice Leader",org:"Ipsos Public Affairs, LLC",vertical:"Federal Civilian",confidence:78,intel:"$35.2M DHA public affairs & program support contract active through Nov 2026. Ipsos does research; Trestleboard does narrative production. Complementary offering.",linkedinSearch:"site:linkedin.com Ipsos Public Affairs Defense Health federal",email:"publicaffairs@ipsos.com (format — verify)",contractRef:"DHA $35.2M active through 2026-11-30",approach:"PARTNERSHIP — Pitch as Ipsos's content execution arm for DHA contract. Research + narrative = complete offering."},
    {id:"disc_008",source:"USAspending.gov — Navy Active Contract",name:"Program Manager",org:"Next Intelligence Solutions, LLC",vertical:"Defense Contractor",confidence:75,intel:"$9.53M Navy administrative/comms support contract through Aug 2026. Veteran-owned small business — strong alignment with Trestleboard's positioning. Recompete window opens early 2026.",linkedinSearch:"site:linkedin.com Next Intelligence Solutions Navy communications",email:"info@nextintelligencesolutions.com (format — verify)",contractRef:"Navy $9.53M expires 2026-08-31",approach:"TEAMING — Small business alignment. Pitch recompete teaming with shared veteran/DoD community positioning."},
    {id:"disc_009",source:"USAspending.gov — USAF Communications Contract",name:"Director of Communications Programs",org:"Innovative Technology Solutions JV, LLC",vertical:"Defense Contractor",confidence:77,intel:"$9.3M USAF Professional Communications Support through June 2027. PSC code = direct comms professional services. Clean contract match to Trestleboard capability. ITS JV is a joint venture looking to grow.",linkedinSearch:"site:linkedin.com Innovative Technology Solutions Air Force communications",email:"bd@itsolvjv.com (format — verify)",contractRef:"USAF $9.3M expires 2027-06-02 PSC:COMMUNICATIONS",approach:"TEAMING — Direct PSC match. Position as AI narrative subcontractor on their USAF communications programs."},
    {id:"disc_010",source:"USAspending.gov + Public Record — Active Buyer",name:"Director, Strategic Communications",org:"Defense Health Agency (DHA)",vertical:"Federal DoD",confidence:83,intel:"DHA is one of the most active DoD comms buyers — multiple large contracts expiring 2026. Active procurement cycle NOW. Office of Communications & Public Affairs at 7700 Arlington Blvd, Falls Church VA. Multiple recompetes in play simultaneously.",linkedinSearch:"site:linkedin.com Defense Health Agency strategic communications director",email:"osd.ha.tricare-mb.mbx.dha-communications@mail.mil (public)",contractRef:"Multiple DHA comms contracts — active buyer cycle",approach:"DIRECT PITCH — DHA is buying now. Position as AI-native narrative vendor. Reference successful DHA contractor models (Ipsos, Chickasaw)."},
    {id:"disc_011",source:"Public Record — Washington Headquarters Services",name:"Contracting Officer / Strategic Comms Director",org:"Washington Headquarters Services (WHS/OSD)",vertical:"Federal DoD",confidence:85,intel:"WHS manages OSD/Pentagon comms contracting. The LMI $83.4M contract EXPIRED July 2025 — WHS is actively recompeting. WHS Acquisition Directorate at the Pentagon holds the vehicle.",linkedinSearch:"site:linkedin.com Washington Headquarters Services strategic communications contracting",email:"whs.pentagon.pnc.mbx.acquisition@mail.mil (public format)",contractRef:"OSD $83.4M LMI contract expired — active recompete",approach:"DIRECT PITCH — Offer as prime or sub on WHS strategic comms recompete. Lead with OSD narrative doctrine alignment and Roman's principal-level access."},
    {id:"disc_012",source:"SOCOM Public Affairs — socom.mil (verified)",name:"Director, USSOCOM Public Affairs",org:"US Special Operations Command (SOCOM) — MacDill AFB",vertical:"Federal DoD",confidence:91,intel:"SOCOM PAO at MacDill AFB, Tampa FL — LOCAL TO ROMAN/SOUTH FLORIDA. Public contact: SOCOM.SOCO.Outreach.DL@socom.mil (verified). SOCOM PAO oversees SOF narrative, internal comms, and community relations. FY2026 budget cycle active. PSYOPs and IO are core SOCOM missions.",linkedinSearch:"site:linkedin.com SOCOM Public Affairs director strategic communications MacDill",email:"SOCOM.SOCO.Outreach.DL@socom.mil (VERIFIED PUBLIC)",contractRef:"SOCOM PAO — MacDill AFB Tampa FL — FY2026 active",approach:"DIRECT PITCH — Geographic proximity advantage (Tampa/South Florida). Lead with SOF operational speed framing, 200+ variant narrative production, sub-1% semantic drift. This is Roman's home turf."}
  ]);

  // ─── Apollo.io Verified Contacts ─────────────────────────────────────
  const APOLLO_VERIFIED_LEADS = Object.freeze([
    {id:"apollo_001",source:"Apollo.io — Verified",name:"Matthew Fay",org:"HII Mission Technologies",vertical:"Defense Contractor",confidence:95,intel:"VP Capture Management — HII $48.7M USAF Info Ops contract EXPIRED Sept 2025. This is the teaming decision-maker for the recompete. Falls Church VA.\n\nApproach: TEAMING — USAF IO narrative recompete. Lead with AI-speed and variant depth.\nEmail (verified): mfay@alionscience.com\nLinkedIn: linkedin.com/in/matthew-fay-b31ab37"},
    {id:"apollo_002",source:"Apollo.io — Verified",name:"Robert Sebastianelli",org:"HII Mission Technologies",vertical:"Defense Contractor",confidence:95,intel:"Capture Director — HII $48.7M USAF contract expired Sept 2025. Capture Director owns the recompete BD. Chantilly VA.\n\nApproach: TEAMING — Direct capture lead. Pitch Trestleboard as AI narrative subcontractor for recompete.\nEmail (verified): robert.sebastianelli@hii.com\nLinkedIn: linkedin.com/in/robert-sebastianelli-4812261a"},
    {id:"apollo_003",source:"Apollo.io — Verified",name:"Jaime Orlando",org:"HII Mission Technologies",vertical:"Defense Contractor",confidence:90,intel:"SVP Communications — oversees all narrative and public affairs across HII contracts. Washington DC.\n\nApproach: PARTNERSHIP — Senior relationship. Position Trestleboard as AI content engine for HII's comms portfolio.\nEmail (verified): jaime.orlando@hii-tsd.com\nLinkedIn: linkedin.com/in/jaimeokeefe"},
    {id:"apollo_004",source:"Apollo.io — Verified",name:"Trish Csank",org:"LMI (Tysons, VA)",vertical:"Defense Contractor",confidence:97,intel:"VP Military Logistics Business Development — LMI holds $83.4M WHS/OSD StrComms contract EXPIRED July 2025. VP BD owns the recompete strategy. THIS IS THE HOTTEST LEAD. Baltimore MD.\n\nApproach: TEAMING — $83M OSD recompete is OPEN NOW. Position Trestleboard as narrative/AI subcontractor on their next WHS bid.\nEmail (verified): patricia.csank@lmi.org\nLinkedIn: linkedin.com/in/trisha-csank"},
    {id:"apollo_005",source:"Apollo.io — Verified",name:"Caitlyn Ottinger",org:"LMI (Tysons, VA)",vertical:"Defense Contractor",confidence:92,intel:"VP Marketing & Communications — internal comms buyer AND external contract strategist. Bristol VT.\n\nApproach: DIRECT — Pitch as AI narrative production partner for LMI's own communications + their OSD contract work.\nEmail (verified): caitlyn.ottinger@lmi.org\nLinkedIn: linkedin.com/in/caitlyn-o-57b7a8170"},
    {id:"apollo_006",source:"Apollo.io — Verified",name:"Marc Melkonian",org:"Booz Allen Hamilton",vertical:"Defense Contractor",confidence:91,intel:"Strategic Capture Director — Booz Allen holds $41.7M USAF + $9.8M DISA comms contracts. Capture Director for DoD accounts. Baltimore MD.\n\nApproach: TEAMING — Position as AI narrative layer under BAH's DoD comms programs.\nEmail (verified): melkonian_marc@bah.com\nLinkedIn: linkedin.com/in/marcmelkonian"},
    {id:"apollo_007",source:"Apollo.io — Verified (Government Buyer)",name:"Whitney Trimble",org:"Defense Health Agency (DHA)",vertical:"Federal DoD",confidence:98,intel:"DIRECT GOVERNMENT BUYER — Director of Public Affairs and Community Outreach at DHA. DHA is spending $35M+ on comms contracts RIGHT NOW. This is the end-client decision-maker. Falls Church VA.\n\nApproach: DIRECT PITCH — DHA is actively buying. Lead with constituent comms acceleration, 200+ variant narrative production. Government email — use formal tone.\nEmail (verified): whitney.trimble@health.mil\nLinkedIn: linkedin.com/in/whitney-trimble-ma-scmp"},
    {id:"apollo_008",source:"Apollo.io — Verified",name:"Scott Gardner",org:"Ipsos Public Affairs",vertical:"Federal Civilian",confidence:88,intel:"VP — Ipsos holds $35.2M DHA Public Affairs contract through Nov 2026. VP is a relationship to lock in for teaming on renewal.\n\nApproach: PARTNERSHIP — Ipsos does research, Trestleboard does narrative execution. Pitch as their content production arm for DHA renewal.\nEmail (verified): scott.gardner@ipsos.com\nLinkedIn: linkedin.com/in/sgardner7"},
    {id:"apollo_009",source:"Apollo.io — Verified",name:"Sanyam Sethi",org:"Ipsos Public Affairs",vertical:"Federal Civilian",confidence:87,intel:"VP Public Affairs — $35.2M DHA contract. Key relationship for teaming on 2026 renewal. Toronto ON.\n\nApproach: PARTNERSHIP — Public Affairs VP is the strongest narrative fit. Ipsos research + Trestleboard narrative = complete offering.\nEmail (verified): sanyam.sethi@ipsos.com\nLinkedIn: linkedin.com/in/sanyamsethi"}
  ]);

  // ─── South Florida + Local Verified Contacts ──────────────────────────
  const SOUTH_FLORIDA_LEADS = Object.freeze([
    {id:"sf_001",source:"Apollo.io — Verified (Miami-Dade Gov)",name:"Kendra Parks",org:"Miami-Dade County",vertical:"Local Government",confidence:91,intel:"Director of Communications — Miami-Dade County. Direct comms buyer for the county's largest municipality. South Florida local.\n\nApproach: DIRECT PITCH — County-level narrative production, constituent communications, press release automation. Lead with speed and volume capability.\nEmail (verified): kendra.parks@miamidade.gov\nLinkedIn: linkedin.com/in/kendraparks"},
    {id:"sf_002",source:"Apollo.io — Verified (Miami-Dade Gov)",name:"Julio Rodriguez",org:"Miami-Dade County",vertical:"Local Government",confidence:90,intel:"Director of Communications — Miami-Dade County. Second comms director — likely owns different portfolio (Spanish-language, outreach, or departmental comms).\n\nApproach: DIRECT PITCH — Bilingual/multicultural narrative production angle. Miami-Dade is majority Spanish-speaking.\nEmail (verified): julio.rodriguez6@miamidade.gov\nLinkedIn: linkedin.com/in/julio-rodriguez-7aa39165"},
    {id:"sf_003",source:"Apollo.io — Verified (Miami-Dade Gov)",name:"Kirsten Castillo",org:"Miami-Dade County",vertical:"Local Government",confidence:88,intel:"Business Development & Public Affairs Manager — Miami-Dade County. Dual BD + public affairs role — rare combo, very relevant to Trestleboard.\n\nApproach: DIRECT PITCH — BD + comms overlap. Perfect entry point for a county-wide narrative contract.\nEmail (verified): kirsten.castillo@miamidade.gov\nLinkedIn: linkedin.com/in/kirsten-castillo-1426a811a"},
    {id:"sf_004",source:"Apollo.io — Verified (Miami-Dade Gov)",name:"Adriana Lamar",org:"Miami-Dade County",vertical:"Local Government",confidence:85,intel:"Public Affairs Manager — Miami-Dade County. Local public affairs contact. South Florida based.\n\nApproach: DIRECT — Intro Trestleboard's AI narrative platform for county public affairs operations.\nEmail (verified): alamar@co.miami-dade.fl.us\nLinkedIn: linkedin.com/in/adriana-lamar-5751b729"},
    {id:"sf_005",source:"Apollo.io — Verified (Miami-Dade Gov)",name:"Ivonne Perez-Suarez",org:"Miami-Dade County Commissioner Office",vertical:"Local Government",confidence:84,intel:"Director of Communications — Commissioner Rebeca Sosa's Office. Direct access to a Miami-Dade Commissioner. Political communications buyer.\n\nApproach: DIRECT — Political narrative/comms production. Spanish-language capability is a major differentiator at the commissioner level.\nEmail (verified): ivonnes@miamidade.gov\nLinkedIn: linkedin.com/in/ivonne-perez-suarez-8b3a253"},
    {id:"sf_006",source:"Apollo.io — Verified (FL Legislature)",name:"Hannah Littlejohn",org:"Florida House of Representatives",vertical:"State Government",confidence:87,intel:"Deputy Communications Director, Office of the Speaker — Florida House of Representatives. This is the Speaker's comms shop. High-volume rapid narrative production is exactly what legislative comms needs.\n\nApproach: DIRECT PITCH — Legislative narrative acceleration, bill communications, constituent messaging at scale.\nEmail (verified): hannah.littlejohn@myfloridahouse.gov\nLinkedIn: linkedin.com/in/hannah-littlejohn-34893a185"},
    {id:"sf_007",source:"Apollo.io — Verified (Miami Chamber)",name:"Alfred Sanchez",org:"Greater Miami Chamber of Commerce",vertical:"Local Business",confidence:93,intel:"President & CEO — Greater Miami Chamber of Commerce. Top business leader in South Florida. Gate to hundreds of Miami businesses. Strategic relationship for BD pipeline development.\n\nApproach: PARTNERSHIP — Position Trestleboard as the Chamber's AI communications partner. Offer member benefit program. This opens doors to the entire South FL business community.\nEmail (verified): asanchez@miamichamber.com\nLinkedIn: linkedin.com/in/alfredsanchez1"},
    {id:"sf_008",source:"Apollo.io — Verified (Miami Chamber)",name:"Susan Snyder",org:"Greater Miami Chamber of Commerce",vertical:"Local Business",confidence:89,intel:"VP Communications — Greater Miami Chamber of Commerce. Fort Lauderdale/South Florida. Owns all Chamber communications — direct buyer for narrative and content production services.\n\nApproach: DIRECT PITCH — Chamber communications production, member spotlights, event narratives. High-volume content need.\nEmail (verified): ssnyder@miamichamber.com\nLinkedIn: linkedin.com/in/suesnyder"},
    {id:"sf_009",source:"Apollo.io — Verified (Miami Chamber)",name:"Jennifer Hanley (via Chamber)",org:"Greater Miami Chamber — L3Harris",vertical:"Defense Contractor",confidence:83,intel:"VP International Business Development & Government Relations — L3Harris Technologies. L3Harris is a major South Florida-headquartered defense prime (Melbourne, FL). Government relations VP = teaming and contract strategy.\n\nApproach: TEAMING — L3Harris does comms systems; Trestleboard does narrative content. Complementary. South Florida proximity.\nEmail (verified): jennifer.hanley@l3harris.com\nLinkedIn: linkedin.com/in/jennifer-hanley-99166422"},
    {id:"sf_010",source:"Apollo.io — Verified (L3Harris FL)",name:"Paul Cvar",org:"L3Harris Technologies",vertical:"Defense Contractor",confidence:88,intel:"Director Capture Management — L3Harris Technologies. L3Harris is Florida-HQ'd defense prime ($18B revenue). Capture Director owns teaming decisions for new bids.\n\nApproach: TEAMING — Pitch Trestleboard as AI narrative layer on L3Harris comms/IO contracts. Florida connection.\nEmail (verified): paul.cvar@l3harris.com\nLinkedIn: linkedin.com/in/pacvar78"},
    {id:"sf_011",source:"Apollo.io — Verified (L3Harris FL)",name:"Kristine Burnell",org:"L3Harris Technologies",vertical:"Defense Contractor",confidence:86,intel:"Director Strategy & Capture — L3Harris. Second capture director. L3Harris wins communications and information operations contracts across DoD.\n\nApproach: TEAMING — AI narrative production as L3Harris subcontractor on IO/comms programs.\nEmail (verified): kristine.burnell@l3harris.com\nLinkedIn: linkedin.com/in/kristine-burnell-0a55142a"},
    {id:"sf_012",source:"Apollo.io — Verified (L3Harris FL)",name:"Genevieve Hamer",org:"L3Harris Technologies",vertical:"Defense Contractor",confidence:85,intel:"Director Strategy & Capture — L3Harris. Third capture director across the L3Harris portfolio. High value for teaming.\n\nApproach: TEAMING — Same L3Harris play. Three capture directors = three shots at a teaming conversation.\nEmail (verified): genevieve.hamer@l3harris.com\nLinkedIn: linkedin.com/in/genevieve-hamer-215892110"}
  ]);

  global.CLAW = global.CLAW || {};
  global.CLAW.CONFIG = CONFIG;
  global.CLAW.AGENT_INTEL_LEADS = AGENT_INTEL_LEADS;
  global.CLAW.APOLLO_VERIFIED_LEADS = APOLLO_VERIFIED_LEADS;
  global.CLAW.SOUTH_FLORIDA_LEADS = SOUTH_FLORIDA_LEADS;
})(window);
